// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCpuFullDetails():Promise<main.CpuFullDetails>;

export function GetCpuFullDetailsJSON():Promise<string>;

export function GetMemoryFullDetails():Promise<main.MemoryDetails>;

export function GetMemoryFullDetailsJSON():Promise<string>;

export function GetRamDetails(arg1:number):Promise<string>;

export function GetSystemDeviceInfo():Promise<main.DeviceInfo>;

export function Greet(arg1:string):Promise<string>;

export function StartMetric(arg1:number):Promise<void>;
