// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfoUpdate() {
  return window['go']['main']['App']['AppInfoUpdate']();
}

export function GenerateDeviceSignature(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateDeviceSignature'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCpuFullDetails() {
  return window['go']['main']['App']['GetCpuFullDetails']();
}

export function GetCpuFullDetailsJSON() {
  return window['go']['main']['App']['GetCpuFullDetailsJSON']();
}

export function GetMemoryFullDetails() {
  return window['go']['main']['App']['GetMemoryFullDetails']();
}

export function GetMemoryFullDetailsJSON() {
  return window['go']['main']['App']['GetMemoryFullDetailsJSON']();
}

export function GetRamDetails(arg1) {
  return window['go']['main']['App']['GetRamDetails'](arg1);
}

export function InitializeFirstTimeSetup() {
  return window['go']['main']['App']['InitializeFirstTimeSetup']();
}

export function SecurityInfoUpdate() {
  return window['go']['main']['App']['SecurityInfoUpdate']();
}

export function StartMetric(arg1) {
  return window['go']['main']['App']['StartMetric'](arg1);
}

export function SystemInfoUpdate() {
  return window['go']['main']['App']['SystemInfoUpdate']();
}
