// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {metric} from '../models';
import {main} from '../models';

export function DashboardUpdate():Promise<metric.DeviceInfo>;

export function GetCpuFullDetails():Promise<main.CpuFullDetails>;

export function GetCpuFullDetailsJSON():Promise<string>;

export function GetMemoryFullDetails():Promise<main.MemoryDetails>;

export function GetMemoryFullDetailsJSON():Promise<string>;

export function GetRamDetails(arg1:number):Promise<string>;

export function StartMetric(arg1:number):Promise<void>;
