// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuFullDetails() {
  return window['go']['main']['App']['GetCpuFullDetails']();
}

export function GetCpuFullDetailsJSON() {
  return window['go']['main']['App']['GetCpuFullDetailsJSON']();
}

export function GetMemoryFullDetails() {
  return window['go']['main']['App']['GetMemoryFullDetails']();
}

export function GetMemoryFullDetailsJSON() {
  return window['go']['main']['App']['GetMemoryFullDetailsJSON']();
}

export function GetRamDetails(arg1) {
  return window['go']['main']['App']['GetRamDetails'](arg1);
}

export function GetSystemDeviceInfo() {
  return window['go']['main']['App']['GetSystemDeviceInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartMetric(arg1) {
  return window['go']['main']['App']['StartMetric'](arg1);
}
