// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfoUpdate():Promise<main.AppInfo>;

export function GenerateDeviceSignature(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetCpuFullDetails():Promise<main.CpuFullDetails>;

export function GetCpuFullDetailsJSON():Promise<string>;

export function GetMemoryFullDetails():Promise<main.MemoryDetails>;

export function GetMemoryFullDetailsJSON():Promise<string>;

export function GetRamDetails(arg1:number):Promise<string>;

export function InitializeFirstTimeSetup():Promise<string>;

export function SecurityInfoUpdate():Promise<main.SecurityInfo>;

export function StartMetric(arg1:number):Promise<void>;

export function SystemInfoUpdate():Promise<main.DeviceInfo>;
