app:
  name: fehmi-agent
  displayName: Fehmi Endpoint Agent
  version: v1.0
  build: 20260622
  environment: development

  company: Fehmi Corporation
  product: Fehmi Unified Endpoint Management

functions:
  - id: 1001
    title: Fehmi Agent Dashboard
    route: dashboard
    layout:
      w: 600
      h: 400
    hide: true
    assets:
      icon: assets/dashboard.ico
    startup: true
    beforeClose: true


tray:
  name: fehmi-tray
  title: Fehmi Agent
  version: v1.0
  tooltip: Fehmi Endpoint Agent

  menu:
    - id: 1
      title: Dashboard      
      tooltip: Show Agent Dashboard
      functionId: 1001
      enabled: true
      visible: true

    - sperator: true

    - id: 2
      title: Sync Now
      tooltip: Run Inventory Scan
      functionId: 2001
      enabled: true
      visible: true

    - id: 3
      title: Status
      tooltip: Show Agent Status
      functionId: 2002
      enabled: true
      visible: true
      
    - id: 3
      title: Request Support
      tooltip: Raise helpdesk support
      functionId: 2003
      enabled: true
      visible: true

    - separator: true

    - id: 3
      title: Exit
      functionId: 9999
      enabled: true
      visible: true
